### ISSUE TITLE
Missing forced blanking implementation

### ISSUE THREAD

**Issue by xTibor** [michelhe/rustboyadvance-ng#102]
This can cause short graphical glitches on scene transitions, when games perform large VRAM updates while expecting the GPU to draw nothing.

The only visible example of this I currently know is the magenta colored screen flash when opening the in-game menu in DBZ Legacy of Goku.

**Comment by michelhe** [comment]
I added a naive approach to force blanking. Visually comparing to mGBA in DBZ Legacy of Goku, it seems about right.
