### ISSUE TITLE
WWF Road to WrestleMania - Invalid mode 6 graphics mode

### ISSUE THREAD

**Issue by xTibor** [michelhe/rustboyadvance-ng#106]
The emulator panics right after the BIOS logo because the game tries to set an invalid, mode 6 graphics mode. Should it be silently ignored? Is this a part of an anti-emulation trick or just garbage game code?

Not to be confused with WWE Road to WrestleMania X8.

**Comment by xTibor** [comment]
The offending game subroutine is at `08018868`. It reads BIOS address `00000500` and moves its value (`d106`) to `DISPCNT`. Thus the mode 6 panic. Still investigating how does it end up reading that bogus address.

**Comment by michelhe** [comment]
I'll try to test in a WIP open-bus branch I have

**Comment by xTibor** [comment]
Yep, it looks like open-bus abuse. Under mGBA it still reads from `00000500` but gets `f004`.

```
 r0: 00000500   r1: 04000000   r2: 00000500   r3: 03000510
 r4: 03000B30   r5: 03000040   r6: 00000000   r7: 03000B30
 r8: 00000000   r9: 00000000  r10: 00000000  r11: 0000001F
r12: 030008D6  r13: 03007EA4  r14: 0803D7B5  r15: 0801887E
cpsr: 0000003F [------T]

0801887C:  8800     	ldrh r0, [r0, #0]

 r0: 0000F004   r1: 04000000   r2: 00000500   r3: 03000510
 r4: 03000B30   r5: 03000040   r6: 00000000   r7: 03000B30
 r8: 00000000   r9: 00000000  r10: 00000000  r11: 0000001F
r12: 030008D6  r13: 03007EA4  r14: 0803D7B5  r15: 08018880
cpsr: 0000003F [------T]

0801887E:  8008     	strh r0, [r1, #0]

 r0: 0000F004   r1: 04000000   r2: 00000500   r3: 03000510
 r4: 03000B30   r5: 03000040   r6: 00000000   r7: 03000B30
 r8: 00000000   r9: 00000000  r10: 00000000  r11: 0000001F
r12: 030008D6  r13: 03007EA4  r14: 0803D7B5  r15: 08018882
cpsr: 0000003F [------T]
```

**Comment by michelhe** [comment]
Confirmed working in my local open-bus branch.
Guess that means I'll have to polish that and merge.

#54
