### ISSUE TITLE
Pokémon GBA Video cartridges - Garbage sprites at the top left corner

### ISSUE THREAD

**Issue by xTibor** [michelhe/rustboyadvance-ng#107]
![Screenshot_20200528_162715](https://user-images.githubusercontent.com/1627292/83159167-fd039400-a105-11ea-8d62-315d0c44f2c8.png)

All four volumes of these Pokémon video cartridges are affected. Other video carts doesn't seem to have these garbage sprites.

**Comment by michelhe** [comment]
Looks like it has to do with bitmap mode frames overlapping with object tiles

**Comment by jsmolka** [comment]
Just lurking around. [This](https://eggcpt.de/eggvance/progress-4/#sprite-tile-restrictions) is the cause.

**Comment by michelhe** [comment]
@jsmolka please lurk more :trophy:

**Comment by michelhe** [comment]
@xTibor @jsmolka BTW, current MGBA also displays these garbage sprites

**Comment by jsmolka** [comment]
Which version are you using? The 0.8.1 works fine for me with Vol. 1.

**Comment by xTibor** [comment]
![Screenshot_20200530_123846](https://user-images.githubusercontent.com/1627292/83326238-8fc14180-a272-11ea-9c72-910577c613f6.png)
https://github.com/mgba-emu/mgba/commit/00aa6476c885fa66e9621960fc9555533ed19bcd

**Comment by michelhe** [comment]
@jsmolka @xTibor  Oh NVM I used v0.8.0 and not v0.8.1
