### ISSUE TITLE
Android Loading of snapshot not working

### ISSUE THREAD

**Issue by idr-pt** [michelhe/rustboyadvance-ng#142]
If i try to load a saved Snapshot in Android the rust emulator hangs with a cracking sound. Please help with any fix

**Comment by michelhe** [comment]
Thx for reporting this,
are you building 'master' ?
can you please post a logcat of the application from the crash ?

**Comment by idr-pt** [comment]
Yes i am building master .Application is not crashing  the emulation just Freezes with crackling voice

here is the log when it Freezes

I/OnePlusAudioTrackInjector: play() packageName: com.mrmichel.rustdroid_emu
I/OnePlusAudioTrackInjector: bufferSizeInBytes:4096, sampleRate:44100
E/AudioSystem-JNI: Command failed for android_media_AudioSystem_setParameters: -1
E/AudioSystem-JNI: Command failed for android_media_AudioSystem_setParameters: -1
D/AudioTrack: ClientUid 10538 AudioTrack::start 
I/Choreographer: Skipped 40 frames!  The application may be doing too much work on its main thread.
D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@b30450b[EmulatorActivity]
I/OpenGLRenderer: Davey! duration=722ms; Flags=1, IntendedVsync=212761978040889, Vsync=212762644707529, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=212762646007533, AnimationStart=212762646261961, PerformTraversalsStart=212762647704513, DrawStart=212762675882429, SyncQueued=212762695044513, SyncStart=212762695439148, IssueDrawCommandsStart=212762695541492, SwapBuffers=212762700134669, FrameCompleted=212762700707221, DequeueBufferDuration=3149000, QueueBufferDuration=129000, 
D/OnePlusJankManager:  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = com.mrmichel.rustdroid_emu/com.mrmichel.rustdroid_emu.ui.snapshots.SnapshotPickerActivity--- jank level = 3
I/OpenGLRenderer: Davey! duration=727ms; Flags=1, IntendedVsync=212761978040889, Vsync=212762644707529, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=212762646007533, AnimationStart=212762646261961, PerformTraversalsStart=212762647704513, DrawStart=212762702102429, SyncQueued=212762704227013, SyncStart=212762704601908, IssueDrawCommandsStart=212762704659721, SwapBuffers=212762705348002, FrameCompleted=212762705897065, DequeueBufferDuration=97000, QueueBufferDuration=120000, 
V/ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed

But there is no Error message . i checked everywhere for error messages in log

**Comment by michelhe** [comment]
I've managed to reproduce on a clean master build (though it had cost me my right ear)
Will look into it, thx!

**Comment by michelhe** [comment]
@idr-pt Can you verify if 46c34ee fixes this on your end ?

**Comment by idr-pt** [comment]
hahaha ... Thanks for prompt resolution. its working now .i also have problem with audio if i turn on turbo mode or change frame rate of emulator... audio cracks and Logs show this message . Games run perfectly but only audio has some cracking

I/chatty: uid=10539(com.mrmichel.rustdroid_emu) Thread-4 identical 25 lines
W/EmulatorBindings: <unknown>: failed to push audio sample
W/EmulatorBindings: <unknown>: failed to push audio sample
I/chatty: uid=10539(com.mrmichel.rustdroid_emu) Thread-4 identical 3752 lines
W/EmulatorBindings: <unknown>: failed to push audio sample
W/EmulatorBindings: <unknown>: failed to push audio sample
I/chatty: uid=10539(com.mrmichel.rustdroid_emu) Thread-4 identical 26652 lines
W/EmulatorBindings: <unknown>: failed to push audio sample
W/EmulatorBindings: <unknown>: failed to push audio sample


Can you tell me its fix also
