### ISSUE TITLE
Audio cracking issue on Android  in turbo mode

### ISSUE THREAD

**Issue by idr-pt** [michelhe/rustboyadvance-ng#143]
i also have problem with audio if i turn on turbo mode or change frame rate of emulator... audio cracks and Logs show this message . Games run perfectly but only audio has some cracking

I/chatty: uid=10539(com.mrmichel.rustdroid_emu) Thread-4 identical 25 lines
W/EmulatorBindings: : failed to push audio sample
W/EmulatorBindings: : failed to push audio sample
I/chatty: uid=10539(com.mrmichel.rustdroid_emu) Thread-4 identical 3752 lines
W/EmulatorBindings: : failed to push audio sample
W/EmulatorBindings: : failed to push audio sample
I/chatty: uid=10539(com.mrmichel.rustdroid_emu) Thread-4 identical 26652 lines
W/EmulatorBindings: : failed to push audio sample
W/EmulatorBindings: : failed to push audio sample

**Comment by michelhe** [comment]
I'm working on a big rewrite of the Java native interface bindings.
For the time being, could you check if removing the `warn!` on lines 50 and 53 mitigates this issue?
https://github.com/michelhe/rustboyadvance-ng/blob/master/bindings/rustboyadvance-jni/src/lib.rs#L50

**Comment by idr-pt** [comment]
removing that lines fixes Cracking to a extent ..its not audible in casual .Thanks for the fix

**Comment by michelhe** [comment]
@idr-pt Hey, I just pushed a big change to master, care to check if this one completely solves it for you  ?

**Comment by idr-pt** [comment]
@michelhe Yes it solves the issue thanks
