### ISSUE TITLE
Display Mode 5 not implemented

### ISSUE THREAD

**Issue by michelhe** [michelhe/rustboyadvance-ng#90]
Never encountered any actual game that uses it though

**Comment by xTibor** [comment]
Spider-Man (intro cinematics) and Blades of Thunder (in-game) uses this mode.

**Comment by jsmolka** [comment]
[This](https://www.gbadev.org/demos.php?showinfo=583) is also an interesting demo which uses a combination of rotation / scaling and mode 5.

**Comment by michelhe** [comment]
Seems to work okay :) 
![image](https://user-images.githubusercontent.com/2903914/83327184-b12a2980-a282-11ea-9960-0df5a871edfc.png)
