### ISSUE TITLE
Super Mario Bros. (Classic NES) - Stuck on the menu screen

### ISSUE THREAD

**Issue by xTibor** [michelhe/rustboyadvance-ng#98]
The menu screen doesn't react to the Start and Select buttons, cannot start a new game. May be related to #95.

**Comment by michelhe** [comment]
I can't reproduce this, I can get into the main menu.
I do get flickering though:
 
![mario glitch](https://user-images.githubusercontent.com/2903914/82670537-fed0e180-9c45-11ea-89d5-4bc5dff99d0b.gif)

**Comment by michelhe** [comment]
@xTibor Which BIOS are you using?

**Comment by xTibor** [comment]
My bad, the ROM I was testing with was underdumped. (`8ca35864ae33c9462dd66ceff1fac5a79e2e0a6f`) Works flawlessly with a correct dump.

The flickering is correct behavior, the game uses interlacing to get higher vertical resolution. It can be made less jarring with interframe blending though.
