### ISSUE TITLE
Dragon Ball Z The Legacy of Goku - Incorrect colors

### ISSUE THREAD

**Issue by xTibor** [michelhe/rustboyadvance-ng#99]
![Screenshot_20200522_102436](https://user-images.githubusercontent.com/1627292/82653851-21500400-9c20-11ea-8353-e2ff0aca02d7.png)

This title text should be black, not magenta. Something is mishandled around transparency/background palette #0 here.

**Comment by michelhe** [comment]
Very similar to what happens to Goku's hair in Dragon Ball Z - Supersonic Warriors

![image](https://user-images.githubusercontent.com/2903914/82670055-24112000-9c45-11ea-83fb-122ee206ad12.png)

**Comment by xTibor** [comment]
https://github.com/michelhe/rustboyadvance-ng/blob/965d4aaae0367be9a7b338fb43cc5cbd07dc5e3b/rustboyadvance-core/src/gpu/rgb15.rs#L18

The magic value chosen for transparent colors is the issue. Games sometimes set the high unused color bit for reasons. In this case Goku's hair is colored `0x8000`, clashing with that transparent constant.

**Comment by michelhe** [comment]
Thanks!
